questions.push(
['Customer value','Why would an enterprise accept the commitment offer?','It earns a concession on planned incremental production use, while existing expected usage keeps its current terms. The customer needs credible expansion plans and enough flexibility to use the allowance.','What if its forecast is uncertain?','Reduce the initial commitment, offer a smaller test, or retain current terms. A larger contract that customers cannot use may harm renewal and trust.'],
['GTM execution','How can this work without bespoke forecasting for every deal?','Start with 15–20 accounts to learn, then use standard spend tiers, a documented trailing-usage baseline, common growth rules and a Finance exception process.','What would you do next Monday?','Partner with GTM on an eligible-account list, establish each organic forecast, document proposed terms and set up a tracking sheet before making offers.'],
['Revenue and cash','Does an annual commitment immediately become revenue?','No. Signed contract value, cash receipts and recognized revenue are different measures. This model forecasts consumption revenue and does not assume unused-credit breakage.','Would you count prepayment as an economic benefit?','Track cash flow and funding benefits separately. Confirm contract-specific revenue treatment with Accounting and avoid counting cash receipts as incremental usage revenue.'],
['Pilot design','How would you choose a control group?','Select comparable accounts or workloads on pre-period usage, growth, model mix and production maturity. Randomize where feasible and establish the measurement window before launch.','What if customers self-select into the offer?','Selection can bias the comparison. Track pre-trends and comparable nonparticipants, and qualify the causal claim rather than attributing all growth to the offer.'],
['Pilot evidence','What can 15–20 enterprise customers actually prove?','They can show customer acceptance, operating friction and early unit economics. The sample may not establish a precise causal portfolio uplift or optimal discount schedule.','When can you scale?','Use a staged expansion once the evidence supports positive incremental economics; continue measurement through the annual term rather than treating a small pilot as final proof.'],
['Resources','What if Engineering can support only one product project?','Prioritize the SOTA latency pilot under this case: the competitive gap is explicit, and modeled economics clear the selected hurdle.','Could reliability take priority instead?','Yes. If outages block production launches or measured reliability returns exceed latency after cost and capacity, I would reprioritize based on that evidence.'],
['Model mix','What does an assumed model mix leave out?','It may miss substitution between tiers, migration across generations and changes in input/output or cached-token mix. Those changes affect both realized price and serving cost.','How would you improve that with internal data?','Build cohort-level token and realized-price histories, then test mix shifts independently from total usage. Keep baseline and plan migration assumptions aligned unless the intervention causes a change.'],
['Forecast horizon','Why only four quarters?','It keeps the forecast decision-focused while making deployment timing visible. Annual contracts starting later continue beyond the horizon, so contract runoff matters.','Is full deployment a Year 2 forecast?','No. It holds the demand assumptions fixed and isolates a full year of operation. A Year 2 forecast also needs organic growth, renewals, model transitions and ongoing costs.'],
['Decision ownership','What are you asking leadership to approve now?','Approve the pilot direction and assign Engineering, GTM and Finance owners to scope funding and measurement. Broad rollout follows measured returns.','Is the modeled implementation amount the pilot budget?','No. The roughly $7M initial-plan implementation input is illustrative deployment spend. Pilot scope, cost and ongoing resources need a separate estimate.'],
['Retention','Could reliability reduce billed tokens by eliminating retries?','Yes. Fewer retries could reduce billed usage even while customer outcomes improve. Measure net consumption, retention and completed production workflows.','Would lower usage mean the project failed?','Not necessarily. Evaluate durable revenue and contribution alongside customer outcomes. The current model focuses on net usage and does not separately quantify long-term retention.'],
['Capacity','Do annual commitments solve spare-capacity problems?','They can improve demand visibility, but a spend commitment does not establish when customers will use capacity. Peak demand and latency requirements still determine serving economics.','What would make the capacity benefit credible?','Measure workload timing, utilization and capacity reservations. Avoid booking a cost saving without evidence of smoother demand or lower effective unit cost.'],
['Pricing mechanics','Why does startup share appear in an all-customer pricing table?','The table measures total portfolio revenue, and the mix changes aggregate elasticity. A higher share of price-inelastic managed startups makes a broad cut less attractive.','Should you compare totals across mixes directly?','Compare each price-cut scenario with its matched 0% row. Changing the customer mix can change the starting revenue, so cross-column totals alone do not isolate price effects.']
);
const decisions=[
{q:'Reliability delivers 5% uplift at a 10% premium. What would you do?',a:['Scale broadly','Keep testing or revise the economics','Claim the full +$80M upside'],correct:1,why:'The combined plan produces about $54M contribution uplift versus current policy, below the initial plan’s $56M. The added reliability result is roughly −$2M.'},
{q:'Acceptance rises, but consumption stays at the organic forecast. Is incremental revenue guaranteed?',a:['Yes—acceptance is revenue','No—consumption and concessions determine the result','Yes—because the contract is annual'],correct:1,why:'Signed commitments and adoption do not create usage revenue by themselves. Check actual consumption, discount scope and accounting treatment.'},
{q:'A 20% cut generates 14% more units. Does it preserve revenue at fixed mix?',a:['Yes','No','Only because compute is cheap'],correct:1,why:'0.80 × 1.14 = 0.912, or an 8.8% revenue decline on that simplified scope. The revenue breakeven is 1 ÷ 0.80 − 1 = 25%.'},
{q:'Latency adds 10 units, reliability 4. With 50% overlap on the smaller benefit, what is combined uplift?',a:['14 units','7 units','12 units'],correct:2,why:'10 + 4 − (50% × 4) = 12. Apply the deduction once; it is already included in the combined workbook forecast.'},
{q:'Would you add +$51M latency, +$5M commitments and +$114M reliability as the recommended total?',a:['Yes','No—use the combined forecast'],correct:1,why:'Standalone grids disable other levers. The combined conditional result is approximately +$136M after interactions, overlap and implementation.'},
{q:'Contribution grows while margin falls 11 bps. Is that automatically a bad investment?',a:['Yes—margin must always rise','No—evaluate dollars, capacity, risk and full cost'],correct:1,why:'The initial plan adds about $56M contribution after implementation. Rate dilution can be acceptable when incremental returns justify the resources.'},
{q:'Serving costs double. Should the recommendation stay unchanged?',a:['Yes—revenue is unchanged','Reassess; reliability may no longer beat the initial plan'],correct:1,why:'The stress calculation reduces initial contribution uplift to roughly $29M and the reliability combination to roughly $28M. Costs can reverse priorities.'}
];
let mode='mixed',decisionIndex=0,answered=false,mathStep=0;
const baseLoad=loadQuestion,baseReveal=revealAnswer,baseRebuttal=revealRebuttal;
function safeRatings(){try{return JSON.parse(localStorage.getItem('ratings')||'{}')}catch{return {}}}
function saveRatings(d){try{localStorage.setItem('ratings',JSON.stringify(d))}catch{}}
function setMode(v){mode=v;document.querySelectorAll('[onclick^="setMode"]').forEach(b=>b.setAttribute('aria-pressed',b.getAttribute('onclick').includes(v)));if(v==='weak'){let r=safeRatings(),weak=questions.map((_,i)=>i).filter(i=>r[i]==='repeat'||r[i]==='okay');if(weak.length){qIndex=weak[0]}else{document.getElementById('question').textContent='Your review basket is empty. Rate a question Almost or Review again to add it here.';['answer','pushback','rebuttal','deepAnswer'].forEach(id=>document.getElementById(id).classList.remove('show'));document.getElementById('questionChoices').innerHTML='';document.getElementById('choiceFeedback').textContent='';document.querySelectorAll('#practice .primary,#pushbackButton,#rebuttalButton,#rating,#deepButton').forEach(e=>e.style.display='none');return;}}loadQuestion();}
loadQuestion=function(){document.querySelector('#practice .primary').style.display='block';document.getElementById('deepButton').style.display='';document.getElementById('deepButton').classList.add('hidden');document.getElementById('deepAnswer').classList.remove('show');document.getElementById('choiceFeedback').textContent='';document.getElementById('questionChoices').innerHTML='';answered=false;if(mode!=='decision'){baseLoad();return;}let d=decisions[decisionIndex];document.getElementById('qCategory').textContent='Decision puzzle '+(decisionIndex+1)+' / '+decisions.length;document.getElementById('question').textContent=d.q;['answer','pushback','rebuttal'].forEach(id=>document.getElementById(id).classList.remove('show'));['pushbackButton','rebuttalButton','rating'].forEach(id=>document.getElementById(id).style.display='none');d.a.forEach((a,i)=>{let b=document.createElement('button');b.className='chip';b.textContent=a;b.onclick=()=>answerDecision(i);document.getElementById('questionChoices').append(b)});};
function answerDecision(i){let d=decisions[decisionIndex];document.getElementById('choiceFeedback').className='feedback';document.getElementById('choiceFeedback').textContent=i===d.correct?'Correct—now connect it to the recommendation.':'Try the reasoning below. This is what practice is for.';document.getElementById('answer').textContent=d.why;document.getElementById('answer').classList.add('show');if(!answered){answered=true;let r=safeRatings();r['decision'+decisionIndex]=i===d.correct?'strong':'repeat';saveRatings(r);updateStatus();}}
revealAnswer=function(){if(mode==='decision'){document.getElementById('answer').textContent=decisions[decisionIndex].why;document.getElementById('answer').classList.add('show');return;}baseReveal();};
revealRebuttal=function(){baseRebuttal();document.getElementById('deepButton').classList.remove('hidden');};
function deepChallenge(){let cat=questions[qIndex][0];document.getElementById('deepAnswer').innerHTML='<strong>Interviewer: “What would you measure first, and what would change your decision?”</strong><p>For '+cat.toLowerCase()+', identify the uncertain input, establish a pre-test baseline, and compare measured incremental contribution with the relevant alternative. Name a concrete stop or revision criterion before expanding.</p><p>Keep the response specific: usage above organic, realized price, effective serving cost, or incremental product benefit after overlap.</p>';document.getElementById('deepAnswer').classList.add('show');}
nextQuestion=function(shuffle){if(mode==='decision'){decisionIndex=(decisionIndex+1)%decisions.length;if(shuffle)decisionIndex=Math.floor(Math.random()*decisions.length);}else if(mode==='weak'){let r=safeRatings(),ids=questions.map((_,i)=>i).filter(i=>r[i]==='repeat'||r[i]==='okay');if(!ids.length){setMode('weak');return;}qIndex=ids[(ids.indexOf(qIndex)+1)%ids.length];}else qIndex=shuffle?(qIndex+1+Math.floor(Math.random()*(questions.length-1)))%questions.length:(qIndex+1)%questions.length;loadQuestion();};
rate=function(v){let r=safeRatings();r[qIndex]=v;saveRatings(r);updateStatus();nextQuestion(false);};
updateStatus=function(){let r=safeRatings(),n=Object.keys(r).length,strong=Object.values(r).filter(v=>v==='strong').length;document.getElementById('progressStatus').textContent=strong+' stars';document.getElementById('questProgress').textContent='Study collection: '+n+' reviewed · '+strong+' confident · '+questions.length+' questions + '+decisions.length+' puzzles';};
function recallMemo(){document.getElementById('memoTalk').classList.add('hidden');document.getElementById('memoRemember').classList.add('hidden');}
function revealMemo(){document.getElementById('memoTalk').classList.remove('hidden');document.getElementById('memoRemember').classList.remove('hidden');}
const oldMemo=loadMemo;loadMemo=function(){oldMemo();revealMemo();};
function bridgeStep(){let lines=['+$90.30M incremental revenue','− $26.83M incremental serving cost','= +$63.47M recurring contribution','− $7.39M implementation','= +$56.08M contribution after implementation'];mathStep=mathStep%5+1;document.getElementById('bridgeSteps').innerHTML=lines.slice(0,mathStep).join('<br>');}
const numberMath=[
'4,224.72 − 4,134.42 = $90.30M. $90.30M ÷ $4,134.42M ≈ 2.18%.',
'$90.30M − $26.83M serving cost − $7.39M implementation = $56.08M.',
'($4,224.72M − $1,050.36M serving cost) ÷ $4,224.72M = 75.14%. Implementation is separate.',
'$135.65M combined contribution uplift − $56.08M initial uplift = $79.57M.',
'With P=1, new P=0.80 and unit cost=0.20: (1−0.20) ÷ (0.80−0.20) −1 = 33.33%.',
'Saved standalone workbook result: $50.95M after implementation. Other incremental levers are off.',
'5% + (56.079−54.125) ÷ (135.653−54.125) × 5 percentage points ≈ 5.12%.',
'Saved commitment-only response at 5% consumption above organic: $6.46M revenue − $1.35M serving cost ≈ $5.11M contribution.'
];
const oldNumber=revealNumber;revealNumber=function(){oldNumber();document.getElementById('numberMeaning').textContent=nums[nIndex][2]+' Math: '+numberMath[nIndex];};
loadMemo();loadQuestion();loadNumber();updateStatus();net();calc();
if('serviceWorker'in navigator){
 const hadController=!!navigator.serviceWorker.controller;let refreshed=false;
 navigator.serviceWorker.addEventListener('controllerchange',()=>{if(hadController&&!refreshed){refreshed=true;location.reload();}});
 navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{});
}
